//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun ac_platformDependentAc(): String = "aJvmServer"
actual fun acServer_platformDependentAcServer(): String = "aJvmServer"
fun aJvmServer_platformOnly() = "aJvmServer"

fun TestAJvmServer() {
  aJvmServer_platformOnly()
  AJvmServerJavaClass().doStuff()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  acServer_platformIndependentAcServer()
  acServer_platformDependentAcServer()
  raJvmServer_platformOnly()
  RaJvmServerJavaClass().doStuff()
}
