//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun raJsServer_platformOnly() = "raJsServer"

fun TestRaJsServer() {
  raJsServer_platformOnly()
}
