//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

expect fun acServer_platformDependentAcServer(): String
fun acServer_platformIndependentAcServer() = "common"

fun TestAcServer() {
  acServer_platformIndependentAcServer()
  acServer_platformDependentAcServer()
  ac_platformIndependentAc()
  ac_platformDependentAc()
}
