//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rJvmServer_platformOnly() = "rJvmServer"

fun TestRJvmServer() {
  rJvmServer_platformOnly()
  RJvmServerJavaClass().doStuff()
  bJvmServer_platformOnly()
  BJvmServerJavaClass().doStuff()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  bcServer_platformIndependentBcServer()
  bcServer_platformDependentBcServer()
  acServer_platformIndependentAcServer()
  acServer_platformDependentAcServer()
  aJvmServer_platformOnly()
  AJvmServerJavaClass().doStuff()
  raJvmServer_platformOnly()
  RaJvmServerJavaClass().doStuff()
  rbJvmServer_platformOnly()
  RbJvmServerJavaClass().doStuff()
}
