//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun raJvmClient_platformOnly() = "raJvmClient"

fun TestRaJvmClient() {
  raJvmClient_platformOnly()
  RaJvmClientJavaClass().doStuff()
}
