//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rbJsServer_platformOnly() = "rbJsServer"

fun TestRbJsServer() {
  rbJsServer_platformOnly()
  raJsServer_platformOnly()
}
