//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJsServer"
actual fun bcServer_platformDependentBcServer(): String = "bJsServer"
fun bJsServer_platformOnly() = "bJsServer"

fun TestBJsServer() {
  bJsServer_platformOnly()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  bcServer_platformIndependentBcServer()
  bcServer_platformDependentBcServer()
  acServer_platformIndependentAcServer()
  acServer_platformDependentAcServer()
  aJsServer_platformOnly()
  raJsServer_platformOnly()
  rbJsServer_platformOnly()
}
