//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

expect fun acClient_platformDependentAcClient(): String
fun acClient_platformIndependentAcClient() = "common"

fun TestAcClient() {
  acClient_platformIndependentAcClient()
  acClient_platformDependentAcClient()
  ac_platformIndependentAc()
  ac_platformDependentAc()
}
