//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

public class RbJvmServerJavaClass {
    public String doStuff() {
       return "rbJvmServer";
    }
}