//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rbJvmClient_platformOnly() = "rbJvmClient"

fun TestRbJvmClient() {
  rbJvmClient_platformOnly()
  RbJvmClientJavaClass().doStuff()
  raJvmClient_platformOnly()
  RaJvmClientJavaClass().doStuff()
}
