//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rbJvmServer_platformOnly() = "rbJvmServer"

fun TestRbJvmServer() {
  rbJvmServer_platformOnly()
  RbJvmServerJavaClass().doStuff()
  raJvmServer_platformOnly()
  RaJvmServerJavaClass().doStuff()
}
