//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun ac_platformDependentAc(): String = "aJsServer"
actual fun acServer_platformDependentAcServer(): String = "aJsServer"
fun aJsServer_platformOnly() = "aJsServer"

fun TestAJsServer() {
  aJsServer_platformOnly()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  acServer_platformIndependentAcServer()
  acServer_platformDependentAcServer()
  raJsServer_platformOnly()
}
