//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJvmClient"
actual fun bcClient_platformDependentBcClient(): String = "bJvmClient"
fun bJvmClient_platformOnly() = "bJvmClient"

fun TestBJvmClient() {
  bJvmClient_platformOnly()
  BJvmClientJavaClass().doStuff()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  bcClient_platformIndependentBcClient()
  bcClient_platformDependentBcClient()
  acClient_platformIndependentAcClient()
  acClient_platformDependentAcClient()
  aJvmClient_platformOnly()
  AJvmClientJavaClass().doStuff()
  raJvmClient_platformOnly()
  RaJvmClientJavaClass().doStuff()
  rbJvmClient_platformOnly()
  RbJvmClientJavaClass().doStuff()
}
