//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun raJsClient_platformOnly() = "raJsClient"

fun TestRaJsClient() {
  raJsClient_platformOnly()
}
