//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rbJsClient_platformOnly() = "rbJsClient"

fun TestRbJsClient() {
  rbJsClient_platformOnly()
  raJsClient_platformOnly()
}
