//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bJsClient"
actual fun bcClient_platformDependentBcClient(): String = "bJsClient"
fun bJsClient_platformOnly() = "bJsClient"

fun TestBJsClient() {
  bJsClient_platformOnly()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  bcClient_platformIndependentBcClient()
  bcClient_platformDependentBcClient()
  acClient_platformIndependentAcClient()
  acClient_platformDependentAcClient()
  aJsClient_platformOnly()
  raJsClient_platformOnly()
  rbJsClient_platformOnly()
}
