//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun rJsClient_platformOnly() = "rJsClient"

fun TestRJsClient() {
  rJsClient_platformOnly()
  bJsClient_platformOnly()
  bc_platformIndependentBc()
  bc_platformDependentBc()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  bcClient_platformIndependentBcClient()
  bcClient_platformDependentBcClient()
  acClient_platformIndependentAcClient()
  acClient_platformDependentAcClient()
  aJsClient_platformOnly()
  raJsClient_platformOnly()
  rbJsClient_platformOnly()
}
