//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

fun raJvmServer_platformOnly() = "raJvmServer"

fun TestRaJvmServer() {
  raJvmServer_platformOnly()
  RaJvmServerJavaClass().doStuff()
}
