//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (called in generateTests)
// from `incremental/multiplatform/multiModule/ultimate/dependencies.txt`
//

actual fun ac_platformDependentAc(): String = "aJvmClient"
actual fun acClient_platformDependentAcClient(): String = "aJvmClient"
fun aJvmClient_platformOnly() = "aJvmClient"

fun TestAJvmClient() {
  aJvmClient_platformOnly()
  AJvmClientJavaClass().doStuff()
  ac_platformIndependentAc()
  ac_platformDependentAc()
  acClient_platformIndependentAcClient()
  acClient_platformDependentAcClient()
  raJvmClient_platformOnly()
  RaJvmClientJavaClass().doStuff()
}
